services:
  mysql:
    image: mysql:8.0
    container_name: opicnic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: opicnic
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - opicnic_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  opicnic-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opicnic_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://opicnic_mysql:3306/opicnic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_AI_STT_BASE_URL=http://opicnic_stt:8000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - opicnic_network

  # --- Monitoring Stack ---

  prometheus:
    image: prom/prometheus:latest
    container_name: opicnic_prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - opicnic_network

  grafana:
    image: grafana/grafana:latest
    container_name: opicnic_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - opicnic_network

networks:
  opicnic_network:
    driver: bridge
