spring.application.name=opicnic

#thymeleaf prefix
spring.thymeleaf.prefix=classpath:/templates/
#suffix
spring.thymeleaf.suffix=.html
#cache
spring.thymeleaf.cache=false

#database
spring.datasource.url=jdbc:mysql://localhost:3306/opicnic
spring.datasource.username=root
spring.datasource.password=dksk1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
#log
spring.jpa.show-sql=true